apiVersion: v1
kind: Secret
metadata:
  name: openvpn-server
data:
  tls.crt: {{ pki "openvpn-server.crt" }}
  tls.key: {{ pki "openvpn-server.key" }}
  ca.crt: {{ pki "openvpn-ca.crt" }}
  dh.pem: {{ pki "openvpn-dh.pem" }}
  server.conf: {{ base64 "openvpn/server.conf" }}
