kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-controller-manager
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      app: kube-controller-manager
  template:
    metadata:
      labels:
        app: kube-controller-manager
    spec:
      tolerations:
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values: ["kube-controller-manager"]
            topologyKey: "kubernetes.io/hostname"
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values: ["kube-controller-manager"]
            topologyKey: "failure-domain.beta.kubernetes.io/zone"
      containers:
      - name: kube-controller-manager
        image: {{ imageFor "hyperkube" }}
        command:
        - hyperkube
        - kube-controller-manager
        args:
        - "--openshift-config=/etc/kubernetes/cmconfig/config.yaml"
        - "--kubeconfig=/etc/kubernetes/secret/kubeconfig"
        volumeMounts:
        - mountPath: /etc/kubernetes/cmconfig
          name: cmconfig
        - mountPath: /etc/kubernetes/config
          name: config
        - mountPath: /etc/kubernetes/secret
          name: secret
        - mountPath: /var/run/kubernetes
          name: certdir
        - mountPath: /var/log/kube-controller-manager
          name: logs
        workingDir: /var/log/kube-controller-manager
      volumes:
      - secret:
          secretName: kube-controller-manager
        name: secret
      - configMap:
          name: kube-controller-manager-config
        name: cmconfig
      - configMap:
          name: kube-controller-manager
        name: config
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: certdir
