apiVersion: v1
kind: Pod
metadata:
  name: auto-approver
spec:
  containers:
  - image: {{ imageFor "cli" }}
    env:
    - name: KUBECONFIG
      value: /etc/openshift/kubeconfig/kubeconfig
    imagePullPolicy: IfNotPresent
    name: autoapprover
    command:
    - /bin/bash
    args:
    - -c
    - |-
      #!/bin/bash
      set -eu
      while true; do
         if oc get csr | grep Pending; then
            oc get csr | grep Pending | awk '{ print $1 }' | xargs oc adm certificate approve
         fi
         sleep 10
      done
    volumeMounts:
    - mountPath: /etc/openshift/kubeconfig
      name: kubeconfig
      readOnly: true
  restartPolicy: Always
  volumes:
  - name: kubeconfig
    secret:
      secretName: service-network-admin-kubeconfig
