kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-controller-manager
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      app: openshift-controller-manager
  template:
    metadata:
      labels:
        app: openshift-controller-manager
    spec:
      automountServiceAccountToken: false
      containers:
      - name: openshift-controller-manager
        image: {{ imageFor "openshift-controller-manager" }}
        command:
        - "openshift-controller-manager"
        args:
        - "start"
        - "--config=/etc/kubernetes/cmconfig/config.yaml"
        volumeMounts:
        - mountPath: /etc/kubernetes/secret
          name: secret
        - mountPath: /etc/kubernetes/cmconfig
          name: cmconfig
        - mountPath: /etc/kubernetes/config
          name: config
      volumes:
      - secret:
          secretName: openshift-controller-manager
        name: secret
      - configMap:
          name: openshift-controller-manager
        name: config
      - configMap:
          name: openshift-controller-manager-config
        name: cmconfig
