apiVersion: v1
kind: Secret
metadata:
  name: oauth-openshift
data:
  kubeconfig: {{ pki "internal-admin.kubeconfig" }}
  server.crt: {{ pki "oauth-openshift.crt" }}
  server.key: {{ pki "oauth-openshift.key" }}
  v4-0-config-system-session: {{ include "oauth-openshift/v4-0-config-system-session.json" | base64  }}
